# fly.toml app configuration file generated for tv-show-game on 2024-09-20T18:47:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-template'
primary_region = 'ewr'

[build]
  # Remove the "builder" line

[build.args]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "npm start"

[env]
  TZ = "America/New_York"
